### PR TITLE
Merge master from react-bootstrap

### PR DESCRIPTION
**Pull request by jerefrer**
I'd like to use the dialogClassName option on the Modal component so I can change the width of the modal, unfortunately it's been available for about a month on react-bootstrap but not on your meteor fork yet.

Apparently the merge is automatic, you would just have to accept the pull request, right ?

### CODE REVIEW

**Comment by dearlordylord** [comment]
Hey Jeremy, thanks for contribution. Won't have time to check code now, but, considering that it is most probably important to you ASAP, I'll just put merge button : )

**Comment by dearlordylord** [comment]
Read your comment, apparently it's just an up-to-date with master. So completely ok. Thanks for PR.

**Comment by dearlordylord** [comment]
Bumped version in Atmosphere. https://atmospherejs.com/firfi/meteor-react-bootstrap

**Comment by jerefrer** [comment]
Awesome, thanks a lot :)

**Comment by jerefrer** [comment]
Mmmh apparently the `dialogClassName` Modal option doesn't seem to work. The css class is not added to the modal element when doing `<ReactBootstrap.Modal dialogClassName='customClass'`>.
Any idea why ?

**Comment by dearlordylord** [comment]
No idea right now. Won't have time to check. What you can do is 1) make sure it is really 0.3 in your system (that's the bumped package version) 2) make dialogClassName option is really in source code 3) try clone repo and symlink to ./packages (I can be not correct here, don't remember if it should be symlink and is dir name is really ./packages)

**Comment by jerefrer** [comment]
The package has been updated : `firfi:meteor-react-bootstrap  upgraded from 0.0.2 to 0.0.3`
But you're right when I search in my home .meteor directory's packages and open the meteor-react-bootstrap.js file (for instance `/home/jeremy/.meteor/packages/firfi_meteor-react-bootstrap/.0.0.3.1u024uf++os+web.browser+web.cordova/web.browser/packages/firfi_meteor-react-bootstrap.js`) I cannot find any mention of `dialogClassName`. For example if you search for the first occurence of `onRequestHide` then you should see `dialogClassName` right under it but it's not there.

Maybe the JS end file hasn't been re-compiled ?

EDIT: Yup, https://github.com/Firfi/meteor-react-bootstrap/blob/master/dist/react-bootstrap.js doesn't mention `dialogClassName` although https://github.com/Firfi/meteor-react-bootstrap/blob/master/src/Modal.js does

**Comment by dearlordylord** [comment]
Ah I see the point. It definitely wasn't. I forgot we have recompile it
each time.

2015-06-14 23:07 GMT+03:00 Jérémy FRERE notifications@github.com:

**Comment by dearlordylord** [comment]
I'm on it, hang on.

2015-06-14 23:10 GMT+03:00 Igor Loskutov igor@loskutoff.com:

**Comment by dearlordylord** [comment]
Should be better now. dialogClassName is there at least.

2015-06-14 23:15 GMT+03:00 Igor Loskutov igor@loskutoff.com:

**Comment by jerefrer** [comment]
I updated the package and `dialogClassName` is now there, yay :)
But it's still not adding the class to the Modal element :'(
Anyway I'll investigate further later in a hardcore debugging session.
Thanks again for your precious time, I'll drop a line when I get the answer.

**Comment by mtscout6** [comment]
@firfi I wasn't aware of a different package manager for meteor as I'm not entirely familiar with that framework. I'm not completely familiar with all the changes that you needed to make to get that package there either. If this is going to garner enough traffic it may be worth tapping into our existing build and release process for this so updates and versions stay inline with each other.

**Comment by dearlordylord** [comment]
@mtscout6 I didn't informed you, as I believe it would be butt pain to do the integration with any build system. Currently Meteor packaging rely _only_ on assigning your package namespace (I.e. `React` or `ReactBootstrap`) to global like this: `ReactBootstrap = ...`. Webpack or browserify want to have some object (i.e. `this`) to work with though. I didn't managed to find a way to do it right and get some global object at least to pass there. Not much help was provided from the meteor community and developers also.

So basically to build meteor package out of webpack, you have to:

1) publish built dist in repo
2) apply special hack to it 

```
var meteorHack = {
  React: React
};
(function webpackUniversalModuleDefinition(root, factory) {
    ...
})(meteorHack, ...) // here, meteorHack instead of this

...

MyLibrary = meteorHack.MyLibrary;

```

I really doubt you would go through it each time or do some special coding. However, if you want take a look and maybe even resolve this issue so it can be done without hack (I wasn't able to) that would've be great.

**Comment by dearlordylord** [comment]
@jerefrer take a look at https://github.com/elidoran/cosmos-browserify/

this issue https://github.com/react-bootstrap/react-bootstrap/issues/837 moved me towards investigating possibilities once more, and it seems that this way which appeared after I made a package is lot more clean. I tried to substitute all my packages with it and it works like a charm. See their example.

**Pull request merged**
